version: '3.8'

services:
  #fast api backend
  api:
    build:
      context: .
      #Change dockerfile based on dev/prod environment
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - mlflow-data:/app/mlruns
    environment:
      - PYTHONUNBUFFERED=1
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow  #doesn't wait for mlflow to be healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.9.2
    ports: 
      - "5003:5000"
    volumes:
      - mlflow-data:/mlflow
    command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "/mlflow", "--default-artifact-root", "/mlflow/artifacts"]
    restart: unless-stopped
    
volumes:
  mlflow-data: